dockitems:
  - name: "Safari"
    path: /Applications/Safari.app
    pos: 1
  - name: "Mail"
    path: /System/Applications/Mail.app
    pos: 2
  - name: "Visual Studio Code"
    path: "\"/Applications/Visual Studio Code.app\""
    pos: 3
  - name: "Messages"
    path: /System/Applications/Messages.app
    pos: 4
  - name: "Calendar"
    path: /System/Applications/Calendar.app
    pos: 5
  - name: "Notes"
    path: /System/Applications/Notes.app
    pos: 6
  - name: "Photos"
    path: /System/Applications/Photos.app
    pos: 7
  - name: "iTerm"
    path: /Applications/iTerm.app
    pos: 8
  - name: "Terminal"
    path: /System/Applications/Utilities/Terminal.app
    pos: 9
  - name: "Console"
    path: /System/Applications/Utilities/Console.app
    pos: 10
  - name: "App Store"
    path: "\"/System/Applications/App Store.app\""
    pos: 11
  - name: "System Settings"
    path: "\"/System/Applications/System Settings.app\""
    pos: 12
  - name: "Applications Folder"
    path: /Applications --section others
    pos: 13
  - name: "Downloads Folder"
    path: ~/Downloads --section others
    pos: 14
