---
# macOS defaults settings
# Phase 1 + Phase 2 migration completed 2025-12-24

defaults:
- domain: com.apple.dock
  key: tilesize
  name: Set Dock tile size to 36 points
  type: int
  value: '36'
- domain: com.apple.dock
  key: orientation
  name: Change Dock's position to the bottom of the screen
  type: string
  value: bottom
- domain: com.apple.dock
  key: autohide
  name: Always display the Dock
  type: bool
  value: 'false'
- domain: com.apple.screensaver
  key: idleTime
  name: Disable the Screensaver
  value: '0'
- domain: com.apple.finder
  key: ShowHardDrivesOnDesktop
  name: Show Drives on the Desktop
  type: bool
  value: 'true'
- domain: com.apple.finder
  key: ShowExternalHardDrivesOnDesktop
  name: Show External Drives on the Desktop
  type: bool
  value: 'true'
- domain: com.apple.finder
  key: ShowRemovableMediaOnDesktop
  name: Show Removable Media on the Desktop
  type: bool
  value: 'true'
- domain: com.apple.finder
  key: AppleShowAllFiles
  name: Show Hidden Files
  type: bool
  value: 'true'
- domain: NSGlobalDomain
  key: AppleShowAllExtensions
  name: Show File Extensions
  type: bool
  value: 'true'
- domain: com.apple.finder
  key: ShowStatusBar
  name: Show the Status Bar in Finder
  type: bool
  value: 'true'
- domain: com.apple.finder
  key: ShowPathbar
  name: Show the Path Bar in Finder
  type: bool
  value: 'true'
- domain: com.apple.TextEdit
  key: RichText
  name: Disable rich text in textedit
  type: bool
  value: 'false'
- domain: NSGlobalDomain
  key: NSTableViewDefaultSizeMode
  name: NSTable View Default Size Mode
  type: int
  value: '2'
- domain: NSGlobalDomain
  key: AppleShowScrollBars
  name: Apple Show Scroll Bars
  type: string
  value: Always
- domain: NSGlobalDomain
  key: NSToolbarTitleViewRolloverDelay
  name: NSToolbar Title View Rollover Delay
  type: float
  value: '0'
- domain: NSGlobalDomain
  key: NSNavPanelExpandedStateForSaveMode
  name: NSNav Panel Expanded State For Save Mode
  type: bool
  value: 'true'
- domain: NSGlobalDomain
  key: NSNavPanelExpandedStateForSaveMode2
  name: NSNav Panel Expanded State For Save Mode2
  type: bool
  value: 'true'
- domain: NSGlobalDomain
  key: PMPrintingExpandedStateForPrint
  name: PMPrinting Expanded State For Print
  type: bool
  value: 'true'
- domain: NSGlobalDomain
  key: PMPrintingExpandedStateForPrint2
  name: PMPrinting Expanded State For Print2
  type: bool
  value: 'true'
- domain: NSGlobalDomain
  key: NSDocumentSaveNewDocumentsToCloud
  name: NSDocument Save New Documents To Cloud
  type: bool
  value: 'false'
- domain: NSGlobalDomain
  key: NSAutomaticCapitalizationEnabled
  name: NSAutomatic Capitalization Enabled
  type: bool
  value: 'false'
- domain: NSGlobalDomain
  key: NSAutomaticDashSubstitutionEnabled
  name: NSAutomatic Dash Substitution Enabled
  type: bool
  value: 'false'
- domain: NSGlobalDomain
  key: NSAutomaticPeriodSubstitutionEnabled
  name: NSAutomatic Period Substitution Enabled
  type: bool
  value: 'false'
- domain: NSGlobalDomain
  key: NSAutomaticQuoteSubstitutionEnabled
  name: NSAutomatic Quote Substitution Enabled
  type: bool
  value: 'false'
- domain: NSGlobalDomain
  key: NSAutomaticSpellingCorrectionEnabled
  name: NSAutomatic Spelling Correction Enabled
  type: bool
  value: 'false'
- domain: NSGlobalDomain
  key: com.apple.mouse.tapBehavior
  name: com.apple.mouse.tap Behavior
  type: int
  value: '1'
- domain: NSGlobalDomain
  key: AppleKeyboardUIMode
  name: Apple Keyboard UIMode
  type: int
  value: '3'
- domain: NSGlobalDomain
  key: ApplePressAndHoldEnabled
  name: Apple Press And Hold Enabled
  type: bool
  value: 'false'
- domain: NSGlobalDomain
  key: AppleLanguages
  name: Apple Languages
  type: array
  value: [de]
- domain: NSGlobalDomain
  key: AppleLocale
  name: Apple Locale
  type: string
  value: de_CH@currency=CHF
- domain: NSGlobalDomain
  key: AppleMeasurementUnits
  name: Apple Measurement Units
  type: string
  value: Centimeters
- domain: NSGlobalDomain
  key: AppleMetricUnits
  name: Apple Metric Units
  type: bool
  value: 'true'
- domain: com.apple.screensaver
  key: askForPassword
  name: ask For Password
  type: int
  value: '1'
- domain: com.apple.screensaver
  key: askForPasswordDelay
  name: ask For Password Delay
  type: int
  value: '0'
- domain: com.apple.screencapture
  key: location
  name: location
  type: string
  value: ${HOME}/Desktop
- domain: com.apple.screencapture
  key: type
  name: type
  type: string
  value: png
- domain: com.apple.screencapture
  key: disable-shadow
  name: disable-shadow
  type: bool
  value: 'true'
- domain: NSGlobalDomain
  key: AppleFontSmoothing
  name: Apple Font Smoothing
  type: int
  value: '1'
- domain: com.apple.finder
  key: QuitMenuItem
  name: Quit Menu Item
  type: bool
  value: 'true'
- domain: com.apple.finder
  key: DisableAllAnimations
  name: Disable All Animations
  type: bool
  value: 'true'
- domain: com.apple.finder
  key: NewWindowTarget
  name: New Window Target
  type: string
  value: PfDe
- domain: com.apple.finder
  key: NewWindowTargetPath
  name: New Window Target Path
  type: string
  value: file://${HOME}/Desktop/
- domain: com.apple.finder
  key: ShowMountedServersOnDesktop
  name: Show Mounted Servers On Desktop
  type: bool
  value: 'true'
- domain: com.apple.finder
  key: _FXShowPosixPathInTitle
  name: FXShow Posix Path In Title
  type: bool
  value: 'true'
- domain: com.apple.finder
  key: _FXSortFoldersFirst
  name: FXSort Folders First
  type: bool
  value: 'true'
- domain: com.apple.finder
  key: FXDefaultSearchScope
  name: FXDefault Search Scope
  type: string
  value: SCcf
- domain: com.apple.finder
  key: FXEnableExtensionChangeWarning
  name: FXEnable Extension Change Warning
  type: bool
  value: 'false'
- domain: NSGlobalDomain
  key: com.apple.springing.enabled
  name: com.apple.springing.enabled
  type: bool
  value: 'true'
- domain: NSGlobalDomain
  key: com.apple.springing.delay
  name: com.apple.springing.delay
  type: float
  value: '0'
- domain: com.apple.finder
  key: OpenWindowForNewRemovableDisk
  name: Open Window For New Removable Disk
  type: bool
  value: 'true'
- domain: com.apple.finder
  key: FXPreferredViewStyle
  name: FXPreferred View Style
  type: string
  value: Nlsv
- domain: com.apple.finder
  key: WarnOnEmptyTrash
  name: Warn On Empty Trash
  type: bool
  value: 'false'
- domain: com.apple.dock
  key: mouse-over-hilite-stack
  name: mouse-over-hilite-stack
  type: bool
  value: 'true'
- domain: com.apple.dock
  key: mineffect
  name: mineffect
  type: string
  value: scale
- domain: com.apple.dock
  key: minimize-to-application
  name: minimize-to-application
  type: bool
  value: 'true'
- domain: com.apple.dock
  key: enable-spring-load-actions-on-all-items
  name: enable-spring-load-actions-on-all-items
  type: bool
  value: 'true'
- domain: com.apple.dock
  key: show-process-indicators
  name: show-process-indicators
  type: bool
  value: 'true'
- domain: com.apple.dock
  key: launchanim
  name: launchanim
  type: bool
  value: 'false'
- domain: com.apple.dock
  key: expose-animation-duration
  name: expose-animation-duration
  type: float
  value: '0.1'
- domain: com.apple.dock
  key: expose-group-by-app
  name: expose-group-by-app
  type: bool
  value: 'false'
- domain: com.apple.dock
  key: dashboard-in-overlay
  name: dashboard-in-overlay
  type: bool
  value: 'true'
- domain: com.apple.dock
  key: mru-spaces
  name: mru-spaces
  type: bool
  value: 'false'
- domain: com.apple.dock
  key: autohide-delay
  name: autohide-delay
  type: float
  value: '0'
- domain: com.apple.dock
  key: autohide-time-modifier
  name: autohide-time-modifier
  type: float
  value: '0'
- domain: com.apple.dock
  key: showhidden
  name: showhidden
  type: bool
  value: 'true'
- domain: com.apple.dock
  key: show-recents
  name: show-recents
  type: bool
  value: 'false'
- domain: com.apple.dock
  key: wvous-tl-corner
  name: wvous-tl-corner
  type: int
  value: '2'
- domain: com.apple.dock
  key: wvous-tl-modifier
  name: wvous-tl-modifier
  type: int
  value: '0'
- domain: com.apple.dock
  key: wvous-tr-corner
  name: wvous-tr-corner
  type: int
  value: '4'
- domain: com.apple.dock
  key: wvous-tr-modifier
  name: wvous-tr-modifier
  type: int
  value: '0'
- domain: com.apple.dock
  key: wvous-bl-corner
  name: wvous-bl-corner
  type: int
  value: '5'
- domain: com.apple.dock
  key: wvous-bl-modifier
  name: wvous-bl-modifier
  type: int
  value: '0'
- domain: NSGlobalDomain
  key: WebKitDeveloperExtras
  name: Web Kit Developer Extras
  type: bool
  value: 'true'
- domain: com.apple.terminal
  key: StringEncodings
  name: String Encodings
  type: array
  value: [4]
- domain: com.apple.terminal
  key: SecureKeyboardEntry
  name: Secure Keyboard Entry
  type: bool
  value: 'true'
- domain: com.apple.Terminal
  key: ShowLineMarks
  name: Show Line Marks
  type: int
  value: '0'
- domain: com.apple.TimeMachine
  key: DoNotOfferNewDisksForBackup
  name: Do Not Offer New Disks For Backup
  type: bool
  value: 'true'
- domain: com.apple.ActivityMonitor
  key: OpenMainWindow
  name: Open Main Window
  type: bool
  value: 'true'
- domain: com.apple.ActivityMonitor
  key: IconType
  name: Icon Type
  type: int
  value: '5'
- domain: com.apple.ActivityMonitor
  key: ShowCategory
  name: Show Category
  type: int
  value: '0'
- domain: com.apple.ActivityMonitor
  key: SortColumn
  name: Sort Column
  type: string
  value: CPUUsage
- domain: com.apple.ActivityMonitor
  key: SortDirection
  name: Sort Direction
  type: int
  value: '0'
- domain: com.apple.TextEdit
  key: PlainTextEncoding
  name: Plain Text Encoding
  type: int
  value: '4'
- domain: com.apple.TextEdit
  key: PlainTextEncodingForWrite
  name: Plain Text Encoding For Write
  type: int
  value: '4'
- domain: com.apple.DiskUtility
  key: DUDebugMenuEnabled
  name: DUDebug Menu Enabled
  type: bool
  value: 'true'
- domain: com.apple.DiskUtility
  key: advanced-image-options
  name: advanced-image-options
  type: bool
  value: 'true'
- domain: com.apple.SoftwareUpdate
  key: AutomaticCheckEnabled
  name: Automatic Check Enabled
  type: bool
  value: 'true'
- domain: com.apple.SoftwareUpdate
  key: ScheduleFrequency
  name: Schedule Frequency
  type: int
  value: '1'
- domain: com.apple.SoftwareUpdate
  key: AutomaticDownload
  name: Automatic Download
  type: int
  value: '1'
- domain: com.apple.SoftwareUpdate
  key: CriticalUpdateInstall
  name: Critical Update Install
  type: int
  value: '1'
