dotfiles_repo: https://github.com/tuxpeople/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_version: main
dotfiles_repo_local_destination: "{{myhomedir}}/development/github/tuxpeople/dotfiles"
dotfiles_files:
  - .aliases
  - .ansible.cfg
  - .bash_profile
  - .bash_prompt
  - .bashrc
  - .config/ghorg
  - .config/git
  - .curlrc
  - .exports
  - .functions
  - .gitattributes
  - .git_config
  - .gitconfig
  - .gitignore
  - .gvimrc
  - .inputrc
  - .macos
  - .screenrc
  - .tmux.conf
  - .wgetrc
  - .vimrc
  - .k9s
  - .zshrc
