---
# List of ansible task files to run after all other tasks are finished.
# Note: Tasks are executed in the order listed below
# Note: Dock configuration moved to tasks/dock.yml (separate file with dock tag)
post_provision_tasks:
  - ../tasks/post/user-config.yml
  - ../tasks/post/various-settings.yml
  - ../tasks/post/bbedit.yml
  - ../tasks/post/github.yml
  - ../tasks/post/dotfiles-remote-ssh.yml
  - ../tasks/post/gpg.yml
  - ../tasks/post/hazel.yml
  - ../tasks/post/iterm2.yml
  - ../tasks/post/printers.yml
  - ../tasks/post/vscode.yml
  - ../tasks/post/{{ myenv }}-settings.yml
